################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Drivers/BSP/Components/ft5336 \
Drivers/BSP/STM32746G-Discovery \
Drivers/CMSIS/DSP_Lib/Source/BasicMathFunctions \
Drivers/CMSIS/DSP_Lib/Source/CommonTables \
Drivers/CMSIS/DSP_Lib/Source/ComplexMathFunctions \
Drivers/CMSIS/DSP_Lib/Source/ControllerFunctions \
Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions \
Drivers/CMSIS/DSP_Lib/Source/FilteringFunctions \
Drivers/CMSIS/DSP_Lib/Source/MatrixFunctions \
Drivers/CMSIS/DSP_Lib/Source/StatisticsFunctions \
Drivers/CMSIS/DSP_Lib/Source/SupportFunctions \
Drivers/CMSIS/DSP_Lib/Source/TransformFunctions \
Drivers/STM32F7xx_HAL_Driver/Src \
Middlewares/ST/TouchGFX/touchgfx/framework/source/platform/driver/touch \
Middlewares/ST/TouchGFX/touchgfx/framework/source/platform/hal/simulator/sdl2 \
Middlewares/ST/TouchGFX/touchgfx/framework/source/touchgfx/containers \
Middlewares/ST/TouchGFX/touchgfx/framework/source/touchgfx/containers/clock \
Middlewares/ST/TouchGFX/touchgfx/framework/source/touchgfx/containers/progress_indicators \
Middlewares/ST/TouchGFX/touchgfx/framework/source/touchgfx/containers/scrollers \
Middlewares/ST/TouchGFX/touchgfx/framework/source/touchgfx/widgets \
Middlewares/ST/TouchGFX/touchgfx/framework/source/touchgfx/widgets/canvas \
Middlewares/ST/TouchGFX/touchgfx/os \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
TouchGFX/build/MINGW32_NT-6.2/generated/fonts/src \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/common \
TouchGFX/build/MINGW32_NT-6.2/generated/gui_generated/src/main_screen \
TouchGFX/build/MINGW32_NT-6.2/generated/images/src \
TouchGFX/build/MINGW32_NT-6.2/generated/images/src/__designer \
TouchGFX/build/MINGW32_NT-6.2/generated/texts/src \
TouchGFX/build/MINGW32_NT-6.2/gui/src/common \
TouchGFX/build/MINGW32_NT-6.2/gui/src/main_screen \
TouchGFX/build/MINGW32_NT-6.2/gui/src/model \
TouchGFX/build/MINGW32_NT-6.2/simulator \
TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/driver/touch \
TouchGFX/build/MINGW32_NT-6.2/touchgfx/framework/source/platform/hal/simulator/sdl2 \
TouchGFX/build/STM32F746-DISCO/Core/Src \
TouchGFX/build/STM32F746-DISCO/Drivers/BSP/Components/ft5336 \
TouchGFX/build/STM32F746-DISCO/Drivers/BSP/STM32746G-Discovery \
TouchGFX/build/STM32F746-DISCO/Drivers/CMSIS/Device/ST/STM32F7xx/Source/Templates/gcc \
TouchGFX/build/STM32F746-DISCO/Drivers/STM32F7xx_HAL_Driver/Src \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/FreeRTOS/Source \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 \
TouchGFX/build/STM32F746-DISCO/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
TouchGFX/build/STM32F746-DISCO/TouchGFX/generated/fonts/src \
TouchGFX/build/STM32F746-DISCO/TouchGFX/generated/gui_generated/src/common \
TouchGFX/build/STM32F746-DISCO/TouchGFX/generated/gui_generated/src/main_screen \
TouchGFX/build/STM32F746-DISCO/TouchGFX/generated/images/src \
TouchGFX/build/STM32F746-DISCO/TouchGFX/generated/texts/src \
TouchGFX/build/STM32F746-DISCO/TouchGFX/gui/src/common \
TouchGFX/build/STM32F746-DISCO/TouchGFX/gui/src/main_screen \
TouchGFX/build/STM32F746-DISCO/TouchGFX/gui/src/model \
TouchGFX/build/STM32F746-DISCO/TouchGFX/os \
TouchGFX/build/STM32F746-DISCO/TouchGFX/target \
TouchGFX/generated/fonts/src \
TouchGFX/generated/gui_generated/src/common \
TouchGFX/generated/gui_generated/src/main_screen \
TouchGFX/generated/images/src \
TouchGFX/generated/texts/src \
TouchGFX/gui/src/common \
TouchGFX/gui/src/main_screen \
TouchGFX/gui/src/model \
TouchGFX/simulator \
TouchGFX/target \
startup \

